# Domain initialization script for Spec-Driven Development
# Creates domain model directory and initializes comprehensive domain template

[CmdletBinding()]
param(
    [switch]$Json,
    [Parameter(ValueFromRemainingArguments=$true)]
    [string[]]$DomainDesc
)

$ErrorActionPreference = "Stop"

# Source common functions
$commonScript = Join-Path $PSScriptRoot 'common.ps1'
. $commonScript

# Find repository root
$repoRoot = Get-RepoRoot
if (-not $repoRoot) {
    Write-Host "ERROR: Could not determine repository root." -ForegroundColor Red
    exit 1
}

# Set up paths
$specifyDir = Join-Path $repoRoot '.specify'
$domainDir = Join-Path $specifyDir 'domain'
$domainFile = Join-Path $domainDir 'domain.md'
$templateFile = Join-Path $repoRoot 'templates/domain-model-template.md'

# Alternative template locations
if (-not (Test-Path $templateFile)) {
    $altTemplate = Join-Path $specifyDir 'templates/domain-model-template.md'
    if (Test-Path $altTemplate) {
        $templateFile = $altTemplate
    }
}

# Create domain directory if it doesn't exist
if (-not (Test-Path $domainDir)) {
    New-Item -ItemType Directory -Path $domainDir -Force | Out-Null
    New-Item -ItemType Directory -Path (Join-Path $domainDir 'contracts') -Force | Out-Null
    Write-Host "✓ Created domain directory: $domainDir" -ForegroundColor Green
} else {
    Write-Host "ℹ Domain directory already exists: $domainDir" -ForegroundColor Cyan
}

# Check if domain model already exists
$domainExists = Test-Path $domainFile
$backupFile = ""
if ($domainExists) {
    # Create backup
    $timestamp = Get-Date -Format 'yyyyMMdd_HHmmss'
    $backupFile = "$domainFile.backup.$timestamp"
    Copy-Item -Path $domainFile -Destination $backupFile
    Write-Host "ℹ Backed up existing domain model to: $backupFile" -ForegroundColor Cyan
}

# Initialize domain file from template
if (-not (Test-Path $templateFile)) {
    Write-Host "ERROR: Domain template not found at: $templateFile" -ForegroundColor Red
    exit 1
}

Copy-Item -Path $templateFile -Destination $domainFile

if ($domainExists) {
    Write-Host "✓ Replaced domain model (backup saved): $domainFile" -ForegroundColor Green
} else {
    Write-Host "✓ Initialized domain model: $domainFile" -ForegroundColor Green
}

# Create supplementary files
$entitiesFile = Join-Path $domainDir 'entities.md'
$eventsFile = Join-Path $domainDir 'events.md'
$contextMapFile = Join-Path $domainDir 'context-map.md'

# Create entities catalog
@'
# Entity Catalog

Quick reference of all entities across bounded contexts.

## By Bounded Context

### [Context Name]

| Entity | Identity | Key Attributes | Aggregates |
|--------|----------|----------------|------------|
| [Entity] | [ID type] | [List] | [Aggregate root or part of] |

## Alphabetical Index

| Entity | Context | Purpose |
|--------|---------|---------|
| [Entity] | [Context] | [Brief description] |

---
*Generated by /speckit.domain - Update as domain evolves*
'@ | Set-Content -Path $entitiesFile

# Create events catalog
@'
# Event Catalog

Complete list of domain events across all bounded contexts.

## Event Index

| Event | Context | Trigger | Data | Consumers |
|-------|---------|---------|------|-----------|
| [Event] | [Context] | [When] | [Fields] | [Who] |

## Event Schemas

### [EventName]

```json
{
  "eventId": "uuid",
  "eventType": "EventName",
  "occurredAt": "ISO8601 timestamp",
  "aggregateId": "uuid",
  "aggregateType": "EntityName",
  "version": 1,
  "data": {
    "field1": "value",
    "field2": "value"
  }
}
```

**Triggered by**: [Action or state change]
**Consumers**: [List of contexts/systems]
**Integration**: [Pub/Sub, Queue, etc.]

---
*Generated by /speckit.domain - Update as domain evolves*
'@ | Set-Content -Path $eventsFile

# Create context map
@'
# Context Map

Visual representation of bounded context relationships and integration patterns.

## Context Relationships

```
┌─────────────────┐
│                 │
│  [Context 1]    │
│  (Upstream)     │
│                 │
└────────┬────────┘
         │
         │ [Integration Pattern]
         │ [Events/API/etc.]
         ▼
┌─────────────────┐
│                 │
│  [Context 2]    │
│  (Downstream)   │
│                 │
└─────────────────┘
```

## Integration Matrix

| From | To | Pattern | Protocol | Data Flow | Consistency |
|------|----|---------| ---------|-----------|-------------|
| [C1] | [C2] | Event | RabbitMQ | Async | Eventual |
| [C2] | [C3] | API | REST | Sync | Strong |

## Dependencies

### [Context Name] depends on:
- [Dependency 1]: [Why and how]
- [Dependency 2]: [Why and how]

---
*Generated by /speckit.domain - Update as domain evolves*
'@ | Set-Content -Path $contextMapFile

Write-Host "✓ Created supplementary files: entities.md, events.md, context-map.md" -ForegroundColor Green

# Get current timestamp
$timestamp = Get-Date -Format 'yyyyMMdd_HHmmss'

# Combine domain description
$domainDescription = if ($DomainDesc) { $DomainDesc -join ' ' } else { '' }

# Output result
if ($Json) {
    $output = @{
        DOMAIN_DIR = $domainDir
        DOMAIN_FILE = $domainFile
        ENTITIES_FILE = $entitiesFile
        EVENTS_FILE = $eventsFile
        CONTEXT_MAP_FILE = $contextMapFile
        CONTRACTS_DIR = Join-Path $domainDir 'contracts'
        DOMAIN_EXISTS = $domainExists
        BACKUP_FILE = $backupFile
        TIMESTAMP = $timestamp
        DOMAIN_DESC = $domainDescription
    }
    $output | ConvertTo-Json
} else {
    Write-Host ""
    Write-Host "Domain Initialization Complete"
    Write-Host "=============================="
    Write-Host "Domain Directory: $domainDir"
    Write-Host "Domain Model: $domainFile"
    Write-Host "Entity Catalog: $entitiesFile"
    Write-Host "Event Catalog: $eventsFile"
    Write-Host "Context Map: $contextMapFile"
    Write-Host "Contracts Dir: $(Join-Path $domainDir 'contracts')"
    Write-Host "Already Existed: $domainExists"
    if ($backupFile) {
        Write-Host "Backup: $backupFile"
    }
    Write-Host "Description: $domainDescription"
}

