#!/usr/bin/env bash
# Domain initialization script for Spec-Driven Development
# Creates domain model directory and initializes comprehensive domain template

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/common.sh"

# Parse arguments
JSON_OUTPUT=false
DOMAIN_DESC=""

while [[ $# -gt 0 ]]; do
  case $1 in
    --json)
      JSON_OUTPUT=true
      shift
      ;;
    *)
      # Accumulate all remaining args as domain description
      DOMAIN_DESC="$*"
      break
      ;;
  esac
done

# Find repository root
REPO_ROOT=$(get_repo_root)
if [[ -z "$REPO_ROOT" ]]; then
  echo "ERROR: Could not determine repository root." >&2
  exit 1
fi

# Set up paths
SPECIFY_DIR="$REPO_ROOT/.specify"
DOMAIN_DIR="$SPECIFY_DIR/domain"
DOMAIN_FILE="$DOMAIN_DIR/domain.md"
TEMPLATE_FILE="$REPO_ROOT/templates/domain-model-template.md"

# Alternative template locations
if [[ ! -f "$TEMPLATE_FILE" ]] && [[ -f "$SPECIFY_DIR/templates/domain-model-template.md" ]]; then
  TEMPLATE_FILE="$SPECIFY_DIR/templates/domain-model-template.md"
fi

# Create domain directory if it doesn't exist
if [[ ! -d "$DOMAIN_DIR" ]]; then
  mkdir -p "$DOMAIN_DIR"
  mkdir -p "$DOMAIN_DIR/contracts"
  echo "✓ Created domain directory: $DOMAIN_DIR" >&2
else
  echo "ℹ Domain directory already exists: $DOMAIN_DIR" >&2
fi

# Check if domain model already exists
DOMAIN_EXISTS=false
BACKUP_FILE=""
if [[ -f "$DOMAIN_FILE" ]]; then
  DOMAIN_EXISTS=true
  # Create backup
  TIMESTAMP=$(date +%Y%m%d_%H%M%S)
  BACKUP_FILE="$DOMAIN_FILE.backup.$TIMESTAMP"
  cp "$DOMAIN_FILE" "$BACKUP_FILE"
  echo "ℹ Backed up existing domain model to: $BACKUP_FILE" >&2
fi

# Initialize domain file from template
if [[ ! -f "$TEMPLATE_FILE" ]]; then
  echo "ERROR: Domain template not found at: $TEMPLATE_FILE" >&2
  exit 1
fi

cp "$TEMPLATE_FILE" "$DOMAIN_FILE"

if [[ "$DOMAIN_EXISTS" = true ]]; then
  echo "✓ Replaced domain model (backup saved): $DOMAIN_FILE" >&2
else
  echo "✓ Initialized domain model: $DOMAIN_FILE" >&2
fi

# Create supplementary files
ENTITIES_FILE="$DOMAIN_DIR/entities.md"
EVENTS_FILE="$DOMAIN_DIR/events.md"
CONTEXT_MAP_FILE="$DOMAIN_DIR/context-map.md"

# Create entities catalog
cat > "$ENTITIES_FILE" << 'EOF'
# Entity Catalog

Quick reference of all entities across bounded contexts.

## By Bounded Context

### [Context Name]

| Entity | Identity | Key Attributes | Aggregates |
|--------|----------|----------------|------------|
| [Entity] | [ID type] | [List] | [Aggregate root or part of] |

## Alphabetical Index

| Entity | Context | Purpose |
|--------|---------|---------|
| [Entity] | [Context] | [Brief description] |

---
*Generated by /speckit.domain - Update as domain evolves*
EOF

# Create events catalog
cat > "$EVENTS_FILE" << 'EOF'
# Event Catalog

Complete list of domain events across all bounded contexts.

## Event Index

| Event | Context | Trigger | Data | Consumers |
|-------|---------|---------|------|-----------|
| [Event] | [Context] | [When] | [Fields] | [Who] |

## Event Schemas

### [EventName]

```json
{
  "eventId": "uuid",
  "eventType": "EventName",
  "occurredAt": "ISO8601 timestamp",
  "aggregateId": "uuid",
  "aggregateType": "EntityName",
  "version": 1,
  "data": {
    "field1": "value",
    "field2": "value"
  }
}
```

**Triggered by**: [Action or state change]
**Consumers**: [List of contexts/systems]
**Integration**: [Pub/Sub, Queue, etc.]

---
*Generated by /speckit.domain - Update as domain evolves*
EOF

# Create context map
cat > "$CONTEXT_MAP_FILE" << 'EOF'
# Context Map

Visual representation of bounded context relationships and integration patterns.

## Context Relationships

```
┌─────────────────┐
│                 │
│  [Context 1]    │
│  (Upstream)     │
│                 │
└────────┬────────┘
         │
         │ [Integration Pattern]
         │ [Events/API/etc.]
         ▼
┌─────────────────┐
│                 │
│  [Context 2]    │
│  (Downstream)   │
│                 │
└─────────────────┘
```

## Integration Matrix

| From | To | Pattern | Protocol | Data Flow | Consistency |
|------|----|---------| ---------|-----------|-------------|
| [C1] | [C2] | Event | RabbitMQ | Async | Eventual |
| [C2] | [C3] | API | REST | Sync | Strong |

## Dependencies

### [Context Name] depends on:
- [Dependency 1]: [Why and how]
- [Dependency 2]: [Why and how]

---
*Generated by /speckit.domain - Update as domain evolves*
EOF

echo "✓ Created supplementary files: entities.md, events.md, context-map.md" >&2

# Get current timestamp
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

# Output result
if [[ "$JSON_OUTPUT" = true ]]; then
  cat <<EOF
{
  "DOMAIN_DIR": "$DOMAIN_DIR",
  "DOMAIN_FILE": "$DOMAIN_FILE",
  "ENTITIES_FILE": "$ENTITIES_FILE",
  "EVENTS_FILE": "$EVENTS_FILE",
  "CONTEXT_MAP_FILE": "$CONTEXT_MAP_FILE",
  "CONTRACTS_DIR": "$DOMAIN_DIR/contracts",
  "DOMAIN_EXISTS": $DOMAIN_EXISTS,
  "BACKUP_FILE": "$BACKUP_FILE",
  "TIMESTAMP": "$TIMESTAMP",
  "DOMAIN_DESC": "$DOMAIN_DESC"
}
EOF
else
  echo ""
  echo "Domain Initialization Complete"
  echo "=============================="
  echo "Domain Directory: $DOMAIN_DIR"
  echo "Domain Model: $DOMAIN_FILE"
  echo "Entity Catalog: $ENTITIES_FILE"
  echo "Event Catalog: $EVENTS_FILE"
  echo "Context Map: $CONTEXT_MAP_FILE"
  echo "Contracts Dir: $DOMAIN_DIR/contracts"
  echo "Already Existed: $DOMAIN_EXISTS"
  if [[ -n "$BACKUP_FILE" ]]; then
    echo "Backup: $BACKUP_FILE"
  fi
  echo "Description: $DOMAIN_DESC"
fi

